---
title: "Inflação acumulada em 12 meses"
author: "Fábio Rocha"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r}

library(GetBCBData)
library(ggplot2)

```

```{r}

# Coletar dados da SELIC no SGS/BCB
inflacao12m = gbcbd_get_series(id = 20716,
                             first.date = "2003-01-01",
                             last.date = Sys.Date())

```

```{r, fig.height=6, fig.width=7}

ggplot(inflacao12m, aes(x = ref.date)) +
  geom_line(aes(y = value), color = "orange", size = 1.3) +
  geom_hline(yintercept = 4.51, colour = 'red', linetype = 'dashed') +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  annotate("rect", fill = "blue", alpha = 0.2,
           xmin = as.Date("2023-08-01"),
           xmax = as.Date("2024-03-15"),
           ymin = -Inf, 
           ymax = Inf) +
  annotate('text',
             x = as.Date("2024-07-01"),
           y = 5.,
           label = '4.51%',
           colour = 'black', size = 5) +
  scale_x_date(date_labels = "%b-%y", date_breaks = "1.5 year") +
  theme(legend.position = 'none',
        plot.title = ggplot2::element_text(face = "bold", size = 13),
        plot.subtitle = ggplot2::element_text(face = "italic"),
        legend.text = ggplot2::element_text(face = "bold"),
        axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(x='', y="%",
     title='	Índice nacional de preços ao consumidor - amplo (IPCA) - em 12 meses',
     subtitle = 'jan/2003 - jan/2024 - Dados: Banco Central')

```

# variação mensal

```{r}

# Coletar dados da SELIC no SGS/BCB
igpm = gbcbd_get_series(id = 189,
                             first.date = "2003-01-01",
                             last.date = Sys.Date())

```

```{r, fig.height=6, fig.width=7}

ggplot(igpm, aes(x = ref.date)) +
  geom_line(aes(y = value), color = "#ed0e58", size = 1.) +
  geom_hline(yintercept = 0, colour = 'blue', linetype = 'dashed') +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  annotate("rect", fill = "blue", alpha = 0.2,
           xmin = as.Date("2023-08-01"),
           xmax = as.Date("2024-03-01"),
           ymin = -Inf, 
           ymax = Inf) +
  annotate('text',
             x = as.Date("2024-07-01"),
           y = .07,
           label = '0.07%',
           colour = 'black', size = 5.5) +
  scale_x_date(date_labels = "%b-%y", date_breaks = "1.5 year") +
  theme(legend.position = 'none',
        plot.title = ggplot2::element_text(face = "bold", size = 13),
        plot.subtitle = ggplot2::element_text(face = "italic"),
        legend.text = ggplot2::element_text(face = "bold"),
        axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(x='', y="%",
     title='Índice geral de preços do mercado (IGP-M)',
     subtitle = 'jan/2003 - jan/2024 - Dados: Banco Central')

```
